# Relaxed rules for blog prose
MD001: false          # Heading increment (blogs use varied structure)
MD007: false          # List indent (allow 4-space)
MD009: false          # Trailing spaces (some intentional for line breaks)
MD013: false          # Line length (prose wraps naturally)
MD024: false          # Duplicate headings (across posts)
MD025: false          # Multiple H1 (blog sections use H1)
MD026: false          # Trailing punctuation in headings
MD032: false          # Blanks around lists (shortcodes)
MD033: false          # Inline HTML (Zola shortcodes)
MD034: false          # Bare URLs (intentional in source lists)
MD036: false          # Emphasis as heading
MD041: false          # First line heading (frontmatter)
MD049: false          # Emphasis style (allow underscore)
MD050: false          # Strong style (allow underscore)
MD052: false          # Reference links (Zola bib shortcode syntax)
